import type { EventSubWsListener } from '@twurple/eventsub-ws';

/**
 * A single field of the Node-RED message payload produced for an EventSub event.
 *
 * - a plain string maps the event property of the same name
 * - `from` reads a differently named event property
 * - `default`/`defaultOn` fill in a missing value (`defaultOn: 'falsy'` mirrors `||`)
 * - `map` derives the value when it is not a straight copy
 */
export type EventSubField =
  | string
  | { key: string; from?: string; default?: unknown; defaultOn?: 'nullish' | 'falsy' }
  | { key: string; map: (event: any) => unknown };

export interface EventSubEventDefinition {
  /** Operation id, e.g. `twitch-eventsub-channel-follow`. */
  type: string;
  /** Dropdown group in the single node's editor, from `categoryFor`. */
  category: string;
  /** Short label shown in the editor dropdown. */
  label: string;
  /** One-line description used in the node help. */
  description: string;
  /** Twurple EventSub listener method invoked for this event. */
  subscribe: (listener: EventSubWsListener, userId: string, cb: (event: any) => void) => void;
  /**
   * Set when Twitch never delivers this topic over the EventSub WebSocket transport.
   * The value is shown to the user and the subscription is skipped.
   */
  unsupportedReason?: string;
  /** Output payload mapping. */
  fields: EventSubField[];
}

/**
 * The entries are declared without a category and get one attached below, so the
 * grouping lives in one place instead of being repeated on every entry. The
 * layout follows Twitch's own grouping of EventSub subscription types; the names
 * are used as the Event dropdown's optgroups inside the `twitch events` node.
 */
type EventSubEventInput = Omit<EventSubEventDefinition, 'category'>;

const EVENT_LIST: EventSubEventInput[] = [
  {
    type: "twitch-eventsub-automod-message-hold",
    label: "automod message hold",
    description: "Fires when AutoMod holds a chat message for review.",
    subscribe: (listener, userId, cb) => listener.onAutoModMessageHoldV2(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "messageId",
      "messageText",
      "messageParts",
      "reason",
      "autoMod",
      "blockedTerms",
      "holdDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-automod-message-update",
    label: "automod message update",
    description: "Fires when a held AutoMod message is approved or denied.",
    subscribe: (listener, userId, cb) => listener.onAutoModMessageUpdateV2(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "messageId",
      "messageText",
      "messageParts",
      "reason",
      "autoMod",
      "blockedTerms",
      "status",
      "holdDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-automod-settings-update",
    label: "automod settings",
    description: "Fires when the AutoMod settings for the channel change.",
    subscribe: (listener, userId, cb) => listener.onAutoModSettingsUpdate(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "overallLevel",
      "aggression",
      "bullying",
      "disability",
      "misogyny",
      "raceEthnicityOrReligion",
      "sexBasedTerms",
      "sexualitySexOrGender",
      "swearing",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-automod-terms-update",
    label: "automod terms",
    description: "Fires when the AutoMod term list for the channel changes.",
    subscribe: (listener, userId, cb) => listener.onAutoModTermsUpdate(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "action",
      "fromAutoMod",
      "terms",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-ad-break-begin",
    label: "ad break begin",
    description: "Fires when a midroll ad break starts in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelAdBreakBegin(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "requesterId",
      "requesterName",
      "requesterDisplayName",
      "durationSeconds",
      "startDate",
      "isAutomatic",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-automatic-reward-redemption-add",
    label: "auto redeem",
    description: "Fires when a redemption is made for an automatically triggered reward.",
    subscribe: (listener, userId, cb) => listener.onChannelAutomaticRewardRedemptionAddV2(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "reward",
      "messageText",
      "messageParts",
      "redemptionDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-ban",
    label: "ban",
    description: "Triggers when a user is banned or timed out in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelBan(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "reason",
      "isPermanent",
      "startDate",
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-bits-use",
    label: "bits use",
    description: "Fires when bits are used to purchase a random Bits-powered emote or extension.",
    subscribe: (listener, userId, cb) => listener.onChannelBitsUse(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "type",
      "bits",
      "messageText",
      "messageParts",
      "powerUp",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-charity-campaign-progress",
    label: "charity progress",
    description: "Fires when progress is made towards a charity campaign.",
    subscribe: (listener, userId, cb) => listener.onChannelCharityCampaignProgress(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "charityName",
      "charityDescription",
      "charityLogo",
      "charityWebsite",
      "currentAmount",
      "targetAmount",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-charity-campaign-start",
    label: "charity start",
    description: "Fires when a charity campaign starts in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelCharityCampaignStart(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "charityName",
      "charityDescription",
      "charityLogo",
      "charityWebsite",
      "currentAmount",
      "targetAmount",
      "startDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-charity-campaign-stop",
    label: "charity stop",
    description: "Fires when a charity campaign stops in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelCharityCampaignStop(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "charityName",
      "charityDescription",
      "charityLogo",
      "charityWebsite",
      "currentAmount",
      "targetAmount",
      "endDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-charity-donation",
    label: "charity donation",
    description: "Fires when a donation is made to a charity campaign.",
    subscribe: (listener, userId, cb) => listener.onChannelCharityDonation(userId, cb),
    fields: [
      "campaignId",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "donorId",
      "donorName",
      "donorDisplayName",
      "charityName",
      "charityDescription",
      "charityLogo",
      "charityWebsite",
      "amount",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-clear-user-messages",
    label: "user messages cleared",
    description: "Fires when the chat messages of a specific user are cleared.",
    subscribe: (listener, userId, cb) => listener.onChannelChatClearUserMessages(userId, userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-clear",
    label: "chat cleared",
    description: "Fires when the chat history in the channel is cleared.",
    subscribe: (listener, userId, cb) => listener.onChannelChatClear(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-message-delete",
    label: "message deleted",
    description: "Fires when a chat message is deleted in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelChatMessageDelete(userId, userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "messageId",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-message",
    label: "chat message",
    description: "Triggers when a chat message is sent to the configured Twitch channel.",
    subscribe: (listener, userId, cb) => listener.onChannelChatMessage(userId, userId, cb),
    fields: [
      "messageId",
      "messageText",
      "messageParts",
      "messageType",
      "chatterId",
      "chatterName",
      "chatterDisplayName",
      "color",
      "badges",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "isCheer",
      "bits",
      { key: "isRedemption", default: false, defaultOn: 'falsy' },
      { key: "isSourceOnly", default: false, defaultOn: 'falsy' },
      { key: "parentMessageId", default: null, defaultOn: 'falsy' },
      { key: "parentMessageText", default: null, defaultOn: 'falsy' },
      { key: "parentMessageUserId", default: null, defaultOn: 'falsy' },
      { key: "parentMessageUserName", default: null, defaultOn: 'falsy' },
      { key: "parentMessageUserDisplayName", default: null, defaultOn: 'falsy' },
      { key: "rewardId", default: null, defaultOn: 'falsy' },
      { key: "sourceBadges", default: null, defaultOn: 'falsy' },
      { key: "sourceBroadcasterId", default: null, defaultOn: 'falsy' },
      { key: "sourceBroadcasterName", default: null, defaultOn: 'falsy' },
      { key: "sourceBroadcasterDisplayName", default: null, defaultOn: 'falsy' },
      { key: "sourceMessageId", default: null, defaultOn: 'falsy' },
      { key: "threadMessageId", default: null, defaultOn: 'falsy' },
      { key: "threadMessageUserId", default: null, defaultOn: 'falsy' },
      { key: "threadMessageUserName", default: null, defaultOn: 'falsy' },
      { key: "threadMessageUserDisplayName", default: null, defaultOn: 'falsy' },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-notification",
    label: "chat notification",
    description: "Fires on chat notifications in the channel: subs, resubs, gift subs, community gifts, raids, announcements, charity donations and bits badge tiers.",
    subscribe: (listener, userId, cb) => listener.onChannelChatNotification(userId, userId, cb),
    fields: [
      "type",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "chatterId",
      "chatterName",
      "chatterDisplayName",
      "chatterIsAnonymous",
      "messageId",
      "messageText",
      "messageParts",
      "color",
      "badges",
      { key: "sourceBroadcasterId", default: null },
      { key: "sourceBroadcasterName", default: null },
      { key: "sourceBroadcasterDisplayName", default: null },
      { key: "sourceMessageId", default: null },
      { key: "sourceBadges", default: null },
      { key: "tier", default: null },
      { key: "isPrime", default: null },
      { key: "durationMonths", default: null },
      { key: "cumulativeMonths", default: null },
      { key: "streakMonths", default: null },
      { key: "isGift", default: null },
      { key: "isGifterAnonymous", default: null },
      { key: "gifterId", default: null },
      { key: "gifterName", default: null },
      { key: "gifterDisplayName", default: null },
      { key: "recipientId", default: null },
      { key: "recipientName", default: null },
      { key: "recipientDisplayName", default: null },
      { key: "communityGiftId", default: null },
      { key: "cumulativeAmount", default: null },
      { key: "raiderId", default: null },
      { key: "raiderName", default: null },
      { key: "raiderDisplayName", default: null },
      { key: "viewerCount", default: null },
      { key: "raiderProfileImageUrl", default: null },
      { key: "charityName", default: null },
      { key: "amount", default: null },
      { key: "newTier", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-settings-update",
    label: "chat settings",
    description: "Fires when the chat settings (emote, follower, slow mode) change.",
    subscribe: (listener, userId, cb) => listener.onChannelChatSettingsUpdate(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "emoteOnlyModeEnabled",
      "followerOnlyModeEnabled",
      "followerOnlyModeDelay",
      "slowModeEnabled",
      "slowModeDelay",
      "subscriberOnlyModeEnabled",
      "uniqueChatModeEnabled",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-user-message-hold",
    label: "user message hold",
    description: "Fires when a chat message from a user is held for review by a moderator.",
    subscribe: (listener, userId, cb) => listener.onChannelChatUserMessageHold(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "messageId",
      "messageText",
      "messageParts",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-chat-user-message-update",
    label: "user message update",
    description: "Fires when a held chat message from a user is approved or denied.",
    subscribe: (listener, userId, cb) => listener.onChannelChatUserMessageUpdate(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "messageId",
      "messageText",
      "messageParts",
      "status",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-cheer",
    label: "cheer",
    description: "Triggers when someone cheers bits in your Twitch channel.",
    subscribe: (listener, userId, cb) => listener.onChannelCheer(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "id",
      "input",
      "redemptionDate",
      "rewardCost",
      "rewardId",
      "rewardPrompt",
      "rewardTitle",
      "status",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-follow",
    label: "follow",
    description: "Triggers when a user follows the specified channel.",
    subscribe: (listener, userId, cb) => listener.onChannelFollow(userId, userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "followDate",
    ],
  },
  {
    type: "twitch-eventsub-channel-goal-begin",
    label: "goal begin",
    description: "Fires when a creator goal starts in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelGoalBegin(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "type",
      "description",
      "currentAmount",
      "targetAmount",
      "startDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-goal-end",
    label: "goal end",
    description: "Fires when a creator goal ends in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelGoalEnd(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "type",
      "description",
      "isAchieved",
      "currentAmount",
      "targetAmount",
      "startDate",
      "endDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-goal-progress",
    label: "goal progress",
    description: "Fires when progress is made towards a creator goal.",
    subscribe: (listener, userId, cb) => listener.onChannelGoalProgress(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "type",
      "description",
      "currentAmount",
      "targetAmount",
      "startDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-hype-train-begin",
    label: "hype train begin",
    description: "Fires when a Hype Train begins in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelHypeTrainBeginV2(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "type",
      "level",
      "total",
      "progress",
      "goal",
      "topContributors",
      "isSharedTrain",
      "sharedTrainParticipants",
      "allTimeHighLevel",
      "allTimeHighTotal",
      "startDate",
      "expiryDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-hype-train-end",
    label: "hype train end",
    description: "Fires when a Hype Train ends in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelHypeTrainEndV2(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "type",
      "level",
      "total",
      "topContributors",
      "isSharedTrain",
      "sharedTrainParticipants",
      "startDate",
      "endDate",
      "cooldownEndDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-hype-train-progress",
    label: "hype train progress",
    description: "Fires on progress towards the next Hype Train level.",
    subscribe: (listener, userId, cb) => listener.onChannelHypeTrainProgressV2(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "type",
      "level",
      "total",
      "progress",
      "goal",
      "topContributors",
      "isSharedTrain",
      "sharedTrainParticipants",
      "startDate",
      "expiryDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-moderation",
    label: "moderation action",
    description: "Fires on any moderation action performed in the channel's chat, such as ban, timeout, unban, clear, delete, raid, mod, vip or warn.",
    subscribe: (listener, userId, cb) => listener.onChannelModerate(userId, userId, cb),
    fields: [
      "moderationAction",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      { key: "userId", default: null },
      { key: "userName", default: null },
      { key: "userDisplayName", default: null },
      { key: "reason", default: null },
      { key: "expiryDate", default: null },
      { key: "messageId", default: null },
      { key: "messageText", default: null },
      { key: "viewerCount", default: null },
      { key: "followDurationMinutes", default: null },
      { key: "waitTimeSeconds", default: null },
      { key: "moderatorMessage", default: null },
      { key: "isApproved", default: null },
      { key: "chatRulesCited", default: [] },
      { key: "terms", default: [] },
      { key: "fromAutoMod", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-moderator-add",
    label: "moderator add",
    description: "Fires when a user is given moderator status in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelModeratorAdd(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-moderator-remove",
    label: "moderator remove",
    description: "Fires when a user loses moderator status in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelModeratorRemove(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-poll-begin",
    label: "poll begin",
    description: "Fires when a poll starts in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelPollBegin(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: 'choices', map: (e: any) => e.choices?.map((c: any) => ({ id: c.id, title: c.title, votes: c.votes ?? 0, channelPointsVotes: c.channelPointsVotes ?? 0, bitsVotes: c.bitsVotes ?? 0 })) ?? [] },
      { key: "bitsVoting", default: null },
      { key: "channelPointsVoting", default: null },
      { key: "status", default: null },
      { key: "startDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-poll-end",
    label: "poll end",
    description: "Fires when a poll ends, including the winning choice.",
    subscribe: (listener, userId, cb) => listener.onChannelPollEnd(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: 'choices', map: (e: any) => e.choices?.map((c: any) => ({ id: c.id, title: c.title, votes: c.votes ?? 0, channelPointsVotes: c.channelPointsVotes ?? 0, bitsVotes: c.bitsVotes ?? 0 })) ?? [] },
      { key: "bitsVoting", default: null },
      { key: "channelPointsVoting", default: null },
      { key: "status", default: null },
      { key: "startDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-poll-progress",
    label: "poll progress",
    description: "Fires when viewers vote in an ongoing poll.",
    subscribe: (listener, userId, cb) => listener.onChannelPollProgress(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: 'choices', map: (e: any) => e.choices?.map((c: any) => ({ id: c.id, title: c.title, votes: c.votes ?? 0, channelPointsVotes: c.channelPointsVotes ?? 0, bitsVotes: c.bitsVotes ?? 0 })) ?? [] },
      { key: "bitsVoting", default: null },
      { key: "channelPointsVoting", default: null },
      { key: "status", default: null },
      { key: "startDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-prediction-begin",
    label: "prediction begin",
    description: "Fires when a prediction starts in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelPredictionBegin(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: "status", default: null },
      { key: "winningOutcomeId", default: null },
      { key: 'outcomes', map: (e: any) => e.outcomes?.map((o: any) => ({ id: o.id, title: o.title, color: o.color, users: o.users ?? 0, channelPoints: o.channelPoints ?? 0 })) ?? [] },
      { key: "startDate", default: null },
      { key: "lockDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-prediction-end",
    label: "prediction end",
    description: "Fires when a prediction ends, including the winning outcome.",
    subscribe: (listener, userId, cb) => listener.onChannelPredictionEnd(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: "status", default: null },
      { key: "winningOutcomeId", default: null },
      { key: 'outcomes', map: (e: any) => e.outcomes?.map((o: any) => ({ id: o.id, title: o.title, color: o.color, users: o.users ?? 0, channelPoints: o.channelPoints ?? 0 })) ?? [] },
      { key: "startDate", default: null },
      { key: "lockDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-prediction-lock",
    label: "prediction lock",
    description: "Fires when a prediction is locked and no longer accepts entries.",
    subscribe: (listener, userId, cb) => listener.onChannelPredictionLock(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: "status", default: null },
      { key: "winningOutcomeId", default: null },
      { key: 'outcomes', map: (e: any) => e.outcomes?.map((o: any) => ({ id: o.id, title: o.title, color: o.color, users: o.users ?? 0, channelPoints: o.channelPoints ?? 0 })) ?? [] },
      { key: "startDate", default: null },
      { key: "lockDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-prediction-progress",
    label: "prediction progress",
    description: "Fires when viewers participate in an ongoing prediction.",
    subscribe: (listener, userId, cb) => listener.onChannelPredictionProgress(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "title",
      { key: "status", default: null },
      { key: "winningOutcomeId", default: null },
      { key: 'outcomes', map: (e: any) => e.outcomes?.map((o: any) => ({ id: o.id, title: o.title, color: o.color, users: o.users ?? 0, channelPoints: o.channelPoints ?? 0 })) ?? [] },
      { key: "startDate", default: null },
      { key: "lockDate", default: null },
      { key: "endDate", default: null },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-raid-from",
    label: "outgoing raid",
    description: "Triggers when this channel raids another channel (outgoing raid).",
    subscribe: (listener, userId, cb) => listener.onChannelRaidFrom(userId, cb),
    fields: [
      { key: "fromBroadcasterId", map: (e: any) => e.raidingBroadcasterId || e.fromBroadcasterId || e.broadcasterId },
      { key: "fromBroadcasterName", map: (e: any) => e.raidingBroadcasterName || e.fromBroadcasterName || e.broadcasterName },
      { key: "fromBroadcasterDisplayName", map: (e: any) => e.raidingBroadcasterDisplayName || e.fromBroadcasterDisplayName || e.broadcasterDisplayName },
      "toBroadcasterId",
      "toBroadcasterName",
      "toBroadcasterDisplayName",
      "viewers",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-raid-to",
    label: "incoming raid",
    description: "Triggers when this channel is raided by another channel (incoming raid).",
    subscribe: (listener, userId, cb) => listener.onChannelRaidTo(userId, cb),
    fields: [
      "fromBroadcasterId",
      "fromBroadcasterName",
      "fromBroadcasterDisplayName",
      { key: "toBroadcasterId", map: (e: any) => e.raidedBroadcasterId || e.toBroadcasterId || e.broadcasterId },
      { key: "toBroadcasterName", map: (e: any) => e.raidedBroadcasterName || e.toBroadcasterName || e.broadcasterName },
      { key: "toBroadcasterDisplayName", map: (e: any) => e.raidedBroadcasterDisplayName || e.toBroadcasterDisplayName || e.broadcasterDisplayName },
      "viewers",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-redemption-add",
    label: "redeem",
    description: "Listens for channel point redemptions in your Twitch channel and outputs the redemption details.",
    subscribe: (listener, userId, cb) => listener.onChannelRedemptionAdd(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "id",
      "input",
      "redemptionDate",
      "rewardCost",
      "rewardId",
      "rewardPrompt",
      "rewardTitle",
      "status",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-redemption-update",
    label: "redeem update",
    description: "Fires when a channel point redemption is updated or cancelled.",
    subscribe: (listener, userId, cb) => listener.onChannelRedemptionUpdate(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "input",
      "status",
      "rewardId",
      "rewardTitle",
      "rewardCost",
      "rewardPrompt",
      "redemptionDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-reward-add",
    label: "reward added",
    description: "Fires when a channel reward is added in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelRewardAdd(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "isEnabled",
      "isPaused",
      "isInStock",
      "title",
      "cost",
      "prompt",
      "userInputRequired",
      "autoApproved",
      "cooldownExpiryDate",
      "redemptionsThisStream",
      "maxRedemptionsPerStream",
      "maxRedemptionsPerUserPerStream",
      "globalCooldown",
      "backgroundColor",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-reward-remove",
    label: "reward removed",
    description: "Fires when a channel reward is removed from the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelRewardRemove(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "isEnabled",
      "isPaused",
      "isInStock",
      "title",
      "cost",
      "prompt",
      "userInputRequired",
      "autoApproved",
      "cooldownExpiryDate",
      "redemptionsThisStream",
      "maxRedemptionsPerStream",
      "maxRedemptionsPerUserPerStream",
      "globalCooldown",
      "backgroundColor",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-reward-update",
    label: "reward updated",
    description: "Fires when a channel reward is updated in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelRewardUpdate(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "isEnabled",
      "isPaused",
      "isInStock",
      "title",
      "cost",
      "prompt",
      "userInputRequired",
      "autoApproved",
      "cooldownExpiryDate",
      "redemptionsThisStream",
      "maxRedemptionsPerStream",
      "maxRedemptionsPerUserPerStream",
      "globalCooldown",
      "backgroundColor",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shared-chat-session-begin",
    label: "shared chat begin",
    description: "Fires when a shared chat session starts in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelSharedChatSessionBegin(userId, cb),
    fields: [
      "sessionId",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "hostBroadcasterId",
      "hostBroadcasterName",
      "hostBroadcasterDisplayName",
      "participants",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shared-chat-session-end",
    label: "shared chat end",
    description: "Fires when a shared chat session ends in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelSharedChatSessionEnd(userId, cb),
    fields: [
      "sessionId",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "hostBroadcasterId",
      "hostBroadcasterName",
      "hostBroadcasterDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shared-chat-session-update",
    label: "shared chat update",
    description: "Fires when a shared chat session is updated.",
    subscribe: (listener, userId, cb) => listener.onChannelSharedChatSessionUpdate(userId, cb),
    fields: [
      "sessionId",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "hostBroadcasterId",
      "hostBroadcasterName",
      "hostBroadcasterDisplayName",
      "participants",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shield-mode-begin",
    label: "shield mode begin",
    description: "Fires when Shield Mode is activated in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelShieldModeBegin(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "startDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shield-mode-end",
    label: "shield mode end",
    description: "Fires when Shield Mode is deactivated in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelShieldModeEnd(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "endDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shoutout-create",
    label: "shoutout create",
    description: "Triggers when the channel sends a shoutout to another broadcaster.",
    subscribe: (listener, userId, cb) => listener.onChannelShoutoutCreate(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "shoutedOutBroadcasterId",
      "shoutedOutBroadcasterName",
      "shoutedOutBroadcasterDisplayName",
      "viewerCount",
      "startDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-shoutout-receive",
    label: "shoutout receive",
    description: "Triggers when the channel receives a shoutout from another broadcaster.",
    subscribe: (listener, userId, cb) => listener.onChannelShoutoutReceive(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "sendingBroadcasterId",
      "sendingBroadcasterName",
      "sendingBroadcasterDisplayName",
      "viewerCount",
      "startDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-stream-offline",
    label: "stream offline",
    description: "Triggers when a stream goes offline in your Twitch channel.",
    subscribe: (listener, userId, cb) => listener.onStreamOffline(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "startDate",
      "type",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-stream-online",
    label: "stream online",
    description: "Triggers when a stream goes live on the configured Twitch channel.",
    subscribe: (listener, userId, cb) => listener.onStreamOnline(userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "startDate",
      "type",
    ],
  },
  {
    type: "twitch-eventsub-channel-subscription-end",
    label: "subscription end",
    description: "Fires when a subscription ends or is renewed down.",
    subscribe: (listener, userId, cb) => listener.onChannelSubscriptionEnd(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "tier",
      "isGift",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-subscription-gift",
    label: "subscription gift",
    description: "Triggers when someone gifts a subscription to another user in your Twitch channel.",
    subscribe: (listener, userId, cb) => listener.onChannelSubscriptionGift(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "gifterId",
      "gifterName",
      "gifterDisplayName",
      "tier",
      "amount",
      "cumulativeAmount",
      "isAnonymous",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-subscription-message",
    label: "subscription message",
    description: "Triggers when a user manually publishes their resubscription milestone anniversary to live chat.",
    subscribe: (listener, userId, cb) => listener.onChannelSubscriptionMessage(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "tier",
      { key: "messageText", default: '' },
      { key: "cumulativeMonths", default: 1 },
      { key: "streakMonths", default: null },
      { key: "durationMonths", default: 1 },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-subscription",
    label: "subscription",
    description: "Triggers instantly when a financial subscription transaction occurs (New Sub, Gift Sub, or Silent Auto-Renewal).",
    subscribe: (listener, userId, cb) => listener.onChannelSubscription(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "tier",
      { key: "isGift", default: false },
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-suspicious-user-message",
    label: "suspicious user message",
    description: "Fires when a message from a suspicious user is sent in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelSuspiciousUserMessage(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "lowTrustStatus",
      "sharedBanChannelIds",
      "types",
      "banEvasionEvaluation",
      "messageId",
      "messageText",
      "messageParts",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-suspicious-user-update",
    label: "suspicious user update",
    description: "Fires when the status of a suspicious user changes.",
    subscribe: (listener, userId, cb) => listener.onChannelSuspiciousUserUpdate(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "lowTrustStatus",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-unban-request-create",
    label: "unban request",
    description: "Fires when a viewer requests to be unbanned in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelUnbanRequestCreate(userId, userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "message",
      "creationDate",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-unban-request-resolve",
    label: "unban request resolved",
    description: "Fires when a moderators unban request is approved or denied.",
    subscribe: (listener, userId, cb) => listener.onChannelUnbanRequestResolve(userId, userId, cb),
    fields: [
      "id",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "resolutionMessage",
      "status",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-unban",
    label: "unban",
    description: "Triggers when a user is unbanned from the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelUnban(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-update",
    label: "channel update",
    description: "Triggers when a broadcaster updates their channel — title, category, or mature content flag.",
    subscribe: (listener, userId, cb) => listener.onChannelUpdate(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      { key: "title", from: "streamTitle" },
      "categoryId",
      "categoryName",
      "isMature",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-vip-add",
    label: "vip add",
    description: "Fires when a user becomes a VIP in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelVipAdd(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-vip-remove",
    label: "vip remove",
    description: "Fires when a user loses VIP status in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelVipRemove(userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-warning-acknowledge",
    label: "warning acknowledged",
    description: "Fires when a viewer acknowledges a chat warning in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelWarningAcknowledge(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-channel-warning-send",
    label: "warning sent",
    description: "Fires when a chat warning is issued to a user in the channel.",
    subscribe: (listener, userId, cb) => listener.onChannelWarningSend(userId, userId, cb),
    fields: [
      "broadcasterId",
      "broadcasterName",
      "broadcasterDisplayName",
      "moderatorId",
      "moderatorName",
      "moderatorDisplayName",
      "userId",
      "userName",
      "userDisplayName",
      "reason",
      "chatRulesCited",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-user-authorization-grant",
    label: "authorization granted",
    description: "Fires when a user grants authorization to an application or extension.",
    subscribe: (listener, userId, cb) => listener.onUserAuthorizationGrant(cb),
    unsupportedReason: `user.authorization.grant is only delivered to webhooks and conduits, not over the EventSub WebSocket transport, so this node will not receive events`,
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "clientId",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-user-authorization-revoke",
    label: "authorization revoked",
    description: "Fires when a user revokes authorization from an application or extension.",
    subscribe: (listener, userId, cb) => listener.onUserAuthorizationRevoke(cb),
    unsupportedReason: `user.authorization.revoke is only delivered to webhooks and conduits, not over the EventSub WebSocket transport, so this node will not receive events`,
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "clientId",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-user-update",
    label: "user updated",
    description: "Fires when the user description or other profile data changes.",
    subscribe: (listener, userId, cb) => listener.onUserUpdate(userId, cb),
    fields: [
      "userId",
      "userName",
      "userDisplayName",
      "userDescription",
      "userEmail",
      "userEmailIsVerified",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
  {
    type: "twitch-eventsub-user-whisper-message",
    label: "whisper received",
    description: "Fires when a whisper message is received by the user.",
    subscribe: (listener, userId, cb) => listener.onUserWhisperMessage(userId, cb),
    fields: [
      "id",
      "userId",
      "userName",
      "userDisplayName",
      "senderUserId",
      "senderUserName",
      "senderUserDisplayName",
      "messageText",
      { key: 'rawEvent', map: (e: any) => e },
    ],
  },
];

function categoryFor(type: string): string {
  const name = type.replace(/^twitch-eventsub-/, '');
  if (/^automod-/.test(name)) return 'automod';
  // The IRC nodes have their own palette entry, so no need to disambiguate here.
  if (/^channel-chat-/.test(name) || /^channel-suspicious-user-/.test(name)) return 'chat events';
  if (/^channel-subscription/.test(name)) return 'subscriptions';
  if (/^channel-(redemption|reward|automatic-reward)/.test(name)) return 'channel points';
  if (/^channel-poll-/.test(name)) return 'polls';
  if (/^channel-prediction-/.test(name)) return 'predictions';
  if (/^channel-hype-train-/.test(name)) return 'hype train';
  if (/^channel-goal-/.test(name)) return 'goals';
  if (/^channel-charity-/.test(name)) return 'charity';
  if (/^channel-(ban|unban|moderator|vip|warning|shield-mode|moderation)/.test(name)) return 'moderation';
  if (/^channel-raid-/.test(name)) return 'raids';
  if (/^channel-(cheer|bits-use|ad-break)/.test(name)) return 'bits & ads';
  if (/^channel-stream-/.test(name)) return 'stream';
  if (/^user-/.test(name)) return 'user';
  return 'channel';
}

export const EVENTS: readonly EventSubEventDefinition[] = EVENT_LIST.map((event) => ({
  ...event,
  category: categoryFor(event.type),
}));

/** The payload key a field maps to, used to document the event in the editor. */
export function fieldKey(field: EventSubField): string {
  return typeof field === 'string' ? field : field.key;
}

export const EVENTS_BY_TYPE: Record<string, EventSubEventDefinition> =
  Object.fromEntries(EVENTS.map((event) => [event.type, event]));
